name: dayily
on:
  workflow_dispatch:

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0 commit hash
      - run: |
          readarray -t pr_nums < <(\
            gh pr list \
              --limit 100 \
              --search "is:open label:duplicate,bug -label:enhancement" \
              --json 'number' \
              --jq '.[].number' \
          )

          for pr_num in "${pr_nums[@]}"; do
              gh pr edit $pr_num --remove-label "duplicate,bug,documentation"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
