name: Dispatcher
on:
  workflow_dispatch:
    inputs:
      dispatched-branch:
        required: true
        default: main
        description: ディスパッチ先のブランチ

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          TOKEN=${{ secrets.PAT }}
          OWNER=miya10kei
          REPO=github-actions-playground2

          BRANCH=$(curl -L https://api.github.com/repos/$OWNER/$REPO/branches \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $TOKEN" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                  | jq -r '.[] | select(.name == "${{ github.ref_name }}") | .name')

          if [ -z "$BRANCH" ]; then
            BRANCH=main

          curl -L -X POST https://api.github.com/repos/$OWNER/$REPO/actions/workflows/74611412/dispatches\
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{ \"ref\": \"$BRANCH\", \"inputs\": { \"ticket-id\": \"Hello\", \"base-branch\": \"develop\" }}"
