name: Dispatcher
on:
  workflow_dispatch:
    inputs:
      dispatched-branch:
        required: true
        default: main
        description: ディスパッチ先のブランチ

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          TOKEN=${{ secrets.PAT }}
          OWNER=miya10kei
          REPO=github-actions-playground2

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/actions/workflows/74611412/dispatches \
            -d '{"ref":"${{ github.event.inputs.dispatched-branch }}","inputs":{"ticket-id":"Hello","base-branch":"develop"}}'
