on:
  push:
    branches:
      - develop
      - staging
  pull_request_target:
    types: [auto_merge_enabled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action@sha256:3320bc61246db3f26fbb36ebade4a220e6f535642dcfd036bebb8516fb4c58cb # v1.7.0

        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "auto_merge"
          RETRY_COUNT: "3"
          RETRY_SLEEP: "5000" # 5秒
          MERGE_CONFLICT_ACTION: "fail"
